---
- name: Instalar LEMP stack ( Nginx, MySQL, PHP)
  hosts: Cliente
  become: yes
  vars:
    mysql_root_password: 1234
  tasks:
    - name: Instalar Nginx
      apt:
        name: nginx
        state: present
      notify: Start Nginx

    - name: Instalar MySQL
      apt:
        name:
          - mysql-server
          - python3-mysqldb
        state: present

    - name: Instalar PHP y sus extensiones
      apt:
        name:
          - php8.1-fpm
          - php-mysql
          - php-mbstring
          - php-xml
          - php-json
          - php-curl
          - php-gd
          - php-zip
          - php-intl
          - php-imagick
          - php-bcmath
          - php-gmp
          - unzip
        state: present
      notify: Restart PHP-FPM

    - name: Crear directorios
      file:
        path: "{{ item.path }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'
      loop:
        - { path: /var/www/wordpress }
        - { path: /var/www/nextcloud }
        - { path: /etc/nginx/ssl }

    - name: Descargar e instalar WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Descomprimir Wordpress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/
        remote_src: yes
        owner: www-data
        group: www-data

    - name: Descargar e instalar Nextcloud
      get_url:
        url: https://download.nextcloud.com/server/releases/latest.tar.bz2
        dest: /tmp/nextcloud.tar.bz2

    - name: Descomprimir nextcloud
      unarchive:
        src: /tmp/nextcloud.tar.bz2
        dest: /var/www/
        remote_src: yes
        owner: www-data
        group: www-data

    - name: Copiar Certificado
      copy:
        src: ./wildcard.demohiberus.com/
        dest: /etc/nginx/ssl

    - name: Copiar wordpress conf
      ansible.builtin.copy:
        src: ./wordnext.conf
        dest: /etc/nginx/sites-available
        mode: '0644'

    - name: Copiar php conf
      ansible.builtin.copy:
        src: ./phpinfo.php
        dest: /var/www/phpinfo.php
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Crear enlace simbolico
      ansible.builtin.file:
        src: /etc/nginx/sites-available/wordnext.conf
        dest: /etc/nginx/sites-enabled/wordnext.conf
        owner: www-data
        group: www-data
        state: link
    - name: Create a new database with name 'wordpressdb'
      mysql_db:
        name: wordpressdb
        state: present

    - name: Create a new database with name 'nextclouddb'
      mysql_db:
        name: nextclouddb
        state: present

    - name: Crear usuario base de datos y darle todos los privilegios
      mysql_user:
        name: azhar
        password: 12345
        priv: '*.*:ALL'
        state: present

  handlers:
    - name: Start Nginx
      systemd:
        name: nginx
        state: started

    - name: Restart PHP-FPM
      systemd:
        name: php8.1-fpm
        state: restarted
